#!/bin/bash

echo "HACKED"

echo "LOL"

echo "noob"

echo "YESSIR"

echo "GET REKT NOOB"

echo "LOLLLLLLLLLLLL"

echo "IM ROBBING YOU!!!!!!"

echo "HACKED"

echo 'yeahhhhhhhh boiiiiiiiiii'

echo 'free m4lw@r3'

echo 'heheheeeeeeeeeeee'

echo 'Im injecting scripts now lol'

echo 'time to get hacked lol


clear

bash spam_script_1
